# build environment
FROM node:14.16.0-alpine as build

WORKDIR /usr/src/client
ENV PATH /usr/src/client/node_modules/.bin:$PATH

COPY ./package.json /usr/src/client/package.json
RUN npm install --silent
RUN npm install @vue/cli@4.5.11 -g

COPY . /usr/src/client
RUN npm run build

# production environment
FROM nginx:1.18.0-alpine

COPY --from=build /usr/src/client/dist /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/default.conf /etc/nginx/conf.d

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]