version: '3.8'

services:
  api:
    container_name: api
    build: 
      context: ./api
      dockerfile: Dockerfile-prod
    command: flask seed-database
    command: gunicorn --bind 0.0.0.0:5000 randomrijks:app
    labels:
      - traefik.http.routers.flask.rule=Host(`api.randomrijks.com`)
      - traefik.http.services.flask.loadbalancer.server.port=5000
      - traefik.http.routers.flask.tls=true
      - traefik.http.routers.flask.tls.certresolver=lets-encrypt
    env_file:
      - ./api/.env
      - ./api/.flaskenv

  client:
    # Initializes an NGINX container responsible for serving the Vue rather than
    # using the npm server command
    container_name: client
    build: 
      context: ./client
      dockerfile: Dockerfile-prod
    labels:
      - traefik.http.routers.client.rule=Host(`randomrijks.com`)
      - traefik.http.services.client.loadbalancer.server.port=8080
      - traefik.http.routers.client.tls=true
      - traefik.http.routers.client.tls.certresolver=lets-encrypt
    env_file:
      - ./client/.env

  reverse-proxy:
    image: traefik:v2.4
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - ./traefik/traefik_dynamic.toml:/etc/traefik/traefik_dynamic.toml
    depends_on:
      - api
      - client
