[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$udIWbcJZ$viwj4qf.6.AKGmLE9WKqN/"
  ]

[http.routers.api]
  rule = "Host(`monitor.randomrijks.com`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"