# pull official base image
FROM python:3.9.2-slim-buster

# set work directory
WORKDIR /usr/src/api

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install psycopg2 dependencies
RUN apt-get update && apt-get install -y libpq-dev gcc

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements-dev.txt /usr/src/api/requirements.txt
RUN pip install -r requirements.txt

# clean psycopg2 dependencies
RUN apt-get autoremove -y gcc

# copy project
COPY . /usr/src/api/